name: bun-astro-garden

services:
  astro-garden:
    build:
      context: .
      dockerfile: bun.Dockerfile
    stdin_open: true
    tty: true
    ports:
      - '4322:4322'
    volumes:
      - /app/node_modules/
      - .:/app
    command: 'bun run dev --port 4322'
