name: astro-garden

services:
  astro-garden:
    container_name: astro-garden
    build:
      context: .
      dockerfile: bun.Dockerfile
    stdin_open: true
    tty: true
    ports:
      - '4321:4321'
    volumes:
      - /app/node_modules/
      - .:/app
    command: 'npm run dev'
