name: node-astro-garden

services:
  astro-garden:
    build:
      context: .
      dockerfile: node.Dockerfile
    stdin_open: true
    tty: true
    ports:
      - '4321:4321'
    volumes:
      - /app/node_modules/
      - .:/app
    command: 'npm run dev'
